/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as RegularVisitorsRouteImport } from './routes/regular-visitors'
import { Route as RequestsRouteImport } from './routes/requests'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SetupAdminRouteImport } from './routes/setup-admin'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as VerifyOtpRouteImport } from './routes/verify-otp'
import { Route as AdminSocietyRouteImport } from './routes/admin/society'
import { Route as AdminVisitorsRouteImport } from './routes/admin/visitors'
import { Route as SecurityAtSecurityRouteImport } from './routes/security/at-security'
import { Route as SecurityOnlineRouteImport } from './routes/security/online'
import { Route as SecurityRegularRouteImport } from './routes/security/regular'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const RegularVisitorsRoute = RegularVisitorsRouteImport.update({
  id: '/regular-visitors',
  path: '/regular-visitors',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsRoute = RequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupAdminRoute = SetupAdminRouteImport.update({
  id: '/setup-admin',
  path: '/setup-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyOtpRoute = VerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSocietyRoute = AdminSocietyRouteImport.update({
  id: '/society',
  path: '/society',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVisitorsRoute = AdminVisitorsRouteImport.update({
  id: '/visitors',
  path: '/visitors',
  getParentRoute: () => AdminRoute,
} as any)
const SecurityAtSecurityRoute = SecurityAtSecurityRouteImport.update({
  id: '/security/at-security',
  path: '/security/at-security',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityOnlineRoute = SecurityOnlineRouteImport.update({
  id: '/security/online',
  path: '/security/online',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRegularRoute = SecurityRegularRouteImport.update({
  id: '/security/regular',
  path: '/security/regular',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/history': typeof HistoryRoute
  '/invite': typeof InviteRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/regular-visitors': typeof RegularVisitorsRoute
  '/requests': typeof RequestsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup-admin': typeof SetupAdminRoute
  '/signup': typeof SignupRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/admin/society': typeof AdminSocietyRoute
  '/admin/visitors': typeof AdminVisitorsRoute
  '/security/at-security': typeof SecurityAtSecurityRoute
  '/security/online': typeof SecurityOnlineRoute
  '/security/regular': typeof SecurityRegularRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/history': typeof HistoryRoute
  '/invite': typeof InviteRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/regular-visitors': typeof RegularVisitorsRoute
  '/requests': typeof RequestsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup-admin': typeof SetupAdminRoute
  '/signup': typeof SignupRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/admin/society': typeof AdminSocietyRoute
  '/admin/visitors': typeof AdminVisitorsRoute
  '/security/at-security': typeof SecurityAtSecurityRoute
  '/security/online': typeof SecurityOnlineRoute
  '/security/regular': typeof SecurityRegularRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/history': typeof HistoryRoute
  '/invite': typeof InviteRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/regular-visitors': typeof RegularVisitorsRoute
  '/requests': typeof RequestsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup-admin': typeof SetupAdminRoute
  '/signup': typeof SignupRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/admin/society': typeof AdminSocietyRoute
  '/admin/visitors': typeof AdminVisitorsRoute
  '/security/at-security': typeof SecurityAtSecurityRoute
  '/security/online': typeof SecurityOnlineRoute
  '/security/regular': typeof SecurityRegularRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/forgot-password'
    | '/history'
    | '/invite'
    | '/login'
    | '/notifications'
    | '/regular-visitors'
    | '/requests'
    | '/reset-password'
    | '/setup-admin'
    | '/signup'
    | '/verify-otp'
    | '/admin/society'
    | '/admin/visitors'
    | '/security/at-security'
    | '/security/online'
    | '/security/regular'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/forgot-password'
    | '/history'
    | '/invite'
    | '/login'
    | '/notifications'
    | '/regular-visitors'
    | '/requests'
    | '/reset-password'
    | '/setup-admin'
    | '/signup'
    | '/verify-otp'
    | '/admin/society'
    | '/admin/visitors'
    | '/security/at-security'
    | '/security/online'
    | '/security/regular'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/forgot-password'
    | '/history'
    | '/invite'
    | '/login'
    | '/notifications'
    | '/regular-visitors'
    | '/requests'
    | '/reset-password'
    | '/setup-admin'
    | '/signup'
    | '/verify-otp'
    | '/admin/society'
    | '/admin/visitors'
    | '/security/at-security'
    | '/security/online'
    | '/security/regular'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HistoryRoute: typeof HistoryRoute
  InviteRoute: typeof InviteRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  RegularVisitorsRoute: typeof RegularVisitorsRoute
  RequestsRoute: typeof RequestsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SetupAdminRoute: typeof SetupAdminRoute
  SignupRoute: typeof SignupRoute
  VerifyOtpRoute: typeof VerifyOtpRoute
  SecurityAtSecurityRoute: typeof SecurityAtSecurityRoute
  SecurityOnlineRoute: typeof SecurityOnlineRoute
  SecurityRegularRoute: typeof SecurityRegularRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regular-visitors': {
      id: '/regular-visitors'
      path: '/regular-visitors'
      fullPath: '/regular-visitors'
      preLoaderRoute: typeof RegularVisitorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests': {
      id: '/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof RequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup-admin': {
      id: '/setup-admin'
      path: '/setup-admin'
      fullPath: '/setup-admin'
      preLoaderRoute: typeof SetupAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-otp': {
      id: '/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof VerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/society': {
      id: '/admin/society'
      path: '/society'
      fullPath: '/admin/society'
      preLoaderRoute: typeof AdminSocietyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/visitors': {
      id: '/admin/visitors'
      path: '/visitors'
      fullPath: '/admin/visitors'
      preLoaderRoute: typeof AdminVisitorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/security/at-security': {
      id: '/security/at-security'
      path: '/security/at-security'
      fullPath: '/security/at-security'
      preLoaderRoute: typeof SecurityAtSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security/online': {
      id: '/security/online'
      path: '/security/online'
      fullPath: '/security/online'
      preLoaderRoute: typeof SecurityOnlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security/regular': {
      id: '/security/regular'
      path: '/security/regular'
      fullPath: '/security/regular'
      preLoaderRoute: typeof SecurityRegularRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminSocietyRoute: typeof AdminSocietyRoute
  AdminVisitorsRoute: typeof AdminVisitorsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminSocietyRoute: AdminSocietyRoute,
  AdminVisitorsRoute: AdminVisitorsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HistoryRoute: HistoryRoute,
  InviteRoute: InviteRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  RegularVisitorsRoute: RegularVisitorsRoute,
  RequestsRoute: RequestsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SetupAdminRoute: SetupAdminRoute,
  SignupRoute: SignupRoute,
  VerifyOtpRoute: VerifyOtpRoute,
  SecurityAtSecurityRoute: SecurityAtSecurityRoute,
  SecurityOnlineRoute: SecurityOnlineRoute,
  SecurityRegularRoute: SecurityRegularRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
