/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as OnlineVisitRouteImport } from './routes/online-visit'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RegisterSocietyRouteImport } from './routes/register-society'
import { Route as RegularVisitorsRouteImport } from './routes/regular-visitors'
import { Route as RequestsRouteImport } from './routes/requests'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SetupAdminRouteImport } from './routes/setup-admin'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as VerifyOtpRouteImport } from './routes/verify-otp'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAnnouncementsRouteImport } from './routes/admin/announcements'
import { Route as AdminResidentsRouteImport } from './routes/admin/residents'
import { Route as AdminSecurityStaffRouteImport } from './routes/admin/security-staff'
import { Route as AdminSocietyRouteImport } from './routes/admin/society'
import { Route as AdminVisitorsRouteImport } from './routes/admin/visitors'
import { Route as SecurityAtSecurityRouteImport } from './routes/security/at-security'
import { Route as SecurityOnlineRouteImport } from './routes/security/online'
import { Route as SecurityRegularRouteImport } from './routes/security/regular'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const OnlineVisitRoute = OnlineVisitRouteImport.update({
  id: '/online-visit',
  path: '/online-visit',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterSocietyRoute = RegisterSocietyRouteImport.update({
  id: '/register-society',
  path: '/register-society',
  getParentRoute: () => rootRouteImport,
} as any)
const RegularVisitorsRoute = RegularVisitorsRouteImport.update({
  id: '/regular-visitors',
  path: '/regular-visitors',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsRoute = RequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupAdminRoute = SetupAdminRouteImport.update({
  id: '/setup-admin',
  path: '/setup-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyOtpRoute = VerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResidentsRoute = AdminResidentsRouteImport.update({
  id: '/residents',
  path: '/residents',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSecurityStaffRoute = AdminSecurityStaffRouteImport.update({
  id: '/security-staff',
  path: '/security-staff',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSocietyRoute = AdminSocietyRouteImport.update({
  id: '/society',
  path: '/society',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVisitorsRoute = AdminVisitorsRouteImport.update({
  id: '/visitors',
  path: '/visitors',
  getParentRoute: () => AdminRoute,
} as any)
const SecurityAtSecurityRoute = SecurityAtSecurityRouteImport.update({
  id: '/security/at-security',
  path: '/security/at-security',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityOnlineRoute = SecurityOnlineRouteImport.update({
  id: '/security/online',
  path: '/security/online',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRegularRoute = SecurityRegularRouteImport.update({
  id: '/security/regular',
  path: '/security/regular',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/history': typeof HistoryRoute
  '/invite': typeof InviteRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/online-visit': typeof OnlineVisitRoute
  '/platform': typeof PlatformRoute
  '/privacy': typeof PrivacyRoute
  '/register-society': typeof RegisterSocietyRoute
  '/regular-visitors': typeof RegularVisitorsRoute
  '/requests': typeof RequestsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/setup-admin': typeof SetupAdminRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/residents': typeof AdminResidentsRoute
  '/admin/security-staff': typeof AdminSecurityStaffRoute
  '/admin/society': typeof AdminSocietyRoute
  '/admin/visitors': typeof AdminVisitorsRoute
  '/security/at-security': typeof SecurityAtSecurityRoute
  '/security/online': typeof SecurityOnlineRoute
  '/security/regular': typeof SecurityRegularRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/history': typeof HistoryRoute
  '/invite': typeof InviteRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/online-visit': typeof OnlineVisitRoute
  '/platform': typeof PlatformRoute
  '/privacy': typeof PrivacyRoute
  '/register-society': typeof RegisterSocietyRoute
  '/regular-visitors': typeof RegularVisitorsRoute
  '/requests': typeof RequestsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/setup-admin': typeof SetupAdminRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/residents': typeof AdminResidentsRoute
  '/admin/security-staff': typeof AdminSecurityStaffRoute
  '/admin/society': typeof AdminSocietyRoute
  '/admin/visitors': typeof AdminVisitorsRoute
  '/security/at-security': typeof SecurityAtSecurityRoute
  '/security/online': typeof SecurityOnlineRoute
  '/security/regular': typeof SecurityRegularRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/history': typeof HistoryRoute
  '/invite': typeof InviteRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/online-visit': typeof OnlineVisitRoute
  '/platform': typeof PlatformRoute
  '/privacy': typeof PrivacyRoute
  '/register-society': typeof RegisterSocietyRoute
  '/regular-visitors': typeof RegularVisitorsRoute
  '/requests': typeof RequestsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/setup-admin': typeof SetupAdminRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/residents': typeof AdminResidentsRoute
  '/admin/security-staff': typeof AdminSecurityStaffRoute
  '/admin/society': typeof AdminSocietyRoute
  '/admin/visitors': typeof AdminVisitorsRoute
  '/security/at-security': typeof SecurityAtSecurityRoute
  '/security/online': typeof SecurityOnlineRoute
  '/security/regular': typeof SecurityRegularRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/forgot-password'
    | '/history'
    | '/invite'
    | '/login'
    | '/notifications'
    | '/online-visit'
    | '/platform'
    | '/privacy'
    | '/register-society'
    | '/regular-visitors'
    | '/requests'
    | '/reset-password'
    | '/settings'
    | '/setup-admin'
    | '/signup'
    | '/terms'
    | '/unauthorized'
    | '/verify-otp'
    | '/admin/announcements'
    | '/admin/residents'
    | '/admin/security-staff'
    | '/admin/society'
    | '/admin/visitors'
    | '/security/at-security'
    | '/security/online'
    | '/security/regular'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/forgot-password'
    | '/history'
    | '/invite'
    | '/login'
    | '/notifications'
    | '/online-visit'
    | '/platform'
    | '/privacy'
    | '/register-society'
    | '/regular-visitors'
    | '/requests'
    | '/reset-password'
    | '/settings'
    | '/setup-admin'
    | '/signup'
    | '/terms'
    | '/unauthorized'
    | '/verify-otp'
    | '/admin/announcements'
    | '/admin/residents'
    | '/admin/security-staff'
    | '/admin/society'
    | '/admin/visitors'
    | '/security/at-security'
    | '/security/online'
    | '/security/regular'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/forgot-password'
    | '/history'
    | '/invite'
    | '/login'
    | '/notifications'
    | '/online-visit'
    | '/platform'
    | '/privacy'
    | '/register-society'
    | '/regular-visitors'
    | '/requests'
    | '/reset-password'
    | '/settings'
    | '/setup-admin'
    | '/signup'
    | '/terms'
    | '/unauthorized'
    | '/verify-otp'
    | '/admin/announcements'
    | '/admin/residents'
    | '/admin/security-staff'
    | '/admin/society'
    | '/admin/visitors'
    | '/security/at-security'
    | '/security/online'
    | '/security/regular'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HistoryRoute: typeof HistoryRoute
  InviteRoute: typeof InviteRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  OnlineVisitRoute: typeof OnlineVisitRoute
  PlatformRoute: typeof PlatformRoute
  PrivacyRoute: typeof PrivacyRoute
  RegisterSocietyRoute: typeof RegisterSocietyRoute
  RegularVisitorsRoute: typeof RegularVisitorsRoute
  RequestsRoute: typeof RequestsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  SetupAdminRoute: typeof SetupAdminRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  VerifyOtpRoute: typeof VerifyOtpRoute
  SecurityAtSecurityRoute: typeof SecurityAtSecurityRoute
  SecurityOnlineRoute: typeof SecurityOnlineRoute
  SecurityRegularRoute: typeof SecurityRegularRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/online-visit': {
      id: '/online-visit'
      path: '/online-visit'
      fullPath: '/online-visit'
      preLoaderRoute: typeof OnlineVisitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register-society': {
      id: '/register-society'
      path: '/register-society'
      fullPath: '/register-society'
      preLoaderRoute: typeof RegisterSocietyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regular-visitors': {
      id: '/regular-visitors'
      path: '/regular-visitors'
      fullPath: '/regular-visitors'
      preLoaderRoute: typeof RegularVisitorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests': {
      id: '/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof RequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup-admin': {
      id: '/setup-admin'
      path: '/setup-admin'
      fullPath: '/setup-admin'
      preLoaderRoute: typeof SetupAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-otp': {
      id: '/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof VerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/announcements': {
      id: '/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/residents': {
      id: '/admin/residents'
      path: '/residents'
      fullPath: '/admin/residents'
      preLoaderRoute: typeof AdminResidentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/security-staff': {
      id: '/admin/security-staff'
      path: '/security-staff'
      fullPath: '/admin/security-staff'
      preLoaderRoute: typeof AdminSecurityStaffRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/society': {
      id: '/admin/society'
      path: '/society'
      fullPath: '/admin/society'
      preLoaderRoute: typeof AdminSocietyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/visitors': {
      id: '/admin/visitors'
      path: '/visitors'
      fullPath: '/admin/visitors'
      preLoaderRoute: typeof AdminVisitorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/security/at-security': {
      id: '/security/at-security'
      path: '/security/at-security'
      fullPath: '/security/at-security'
      preLoaderRoute: typeof SecurityAtSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security/online': {
      id: '/security/online'
      path: '/security/online'
      fullPath: '/security/online'
      preLoaderRoute: typeof SecurityOnlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security/regular': {
      id: '/security/regular'
      path: '/security/regular'
      fullPath: '/security/regular'
      preLoaderRoute: typeof SecurityRegularRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRoute
  AdminResidentsRoute: typeof AdminResidentsRoute
  AdminSecurityStaffRoute: typeof AdminSecurityStaffRoute
  AdminSocietyRoute: typeof AdminSocietyRoute
  AdminVisitorsRoute: typeof AdminVisitorsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnnouncementsRoute: AdminAnnouncementsRoute,
  AdminResidentsRoute: AdminResidentsRoute,
  AdminSecurityStaffRoute: AdminSecurityStaffRoute,
  AdminSocietyRoute: AdminSocietyRoute,
  AdminVisitorsRoute: AdminVisitorsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HistoryRoute: HistoryRoute,
  InviteRoute: InviteRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  OnlineVisitRoute: OnlineVisitRoute,
  PlatformRoute: PlatformRoute,
  PrivacyRoute: PrivacyRoute,
  RegisterSocietyRoute: RegisterSocietyRoute,
  RegularVisitorsRoute: RegularVisitorsRoute,
  RequestsRoute: RequestsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  SetupAdminRoute: SetupAdminRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  VerifyOtpRoute: VerifyOtpRoute,
  SecurityAtSecurityRoute: SecurityAtSecurityRoute,
  SecurityOnlineRoute: SecurityOnlineRoute,
  SecurityRegularRoute: SecurityRegularRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
