package com.societyone.app.society.dto;

import com.societyone.app.society.entity.SocietyCreationRequest;

public record SocietyCreationRequestResponse(
        Long id,
        String referenceCode,
        String primaryContactName,
        String primaryContactEmail,
        String primaryContactPhone,
        String societyOfficialEmail,
        String secondaryContactName,
        String secondaryContactPhone,
        String secondaryContactEmail,
        String societyName,
        String registrationNumber,
        String societyType,
        Integer totalFlats,
        Integer numberOfWings,
        String address,
        String city,
        String state,
        String postalCode,
        String managementMethod,
        String documentUrl,
        String documentFilename,
        Long documentSizeBytes,
        String status,
        Long reviewerUserId,
        String reviewerName,
        String reviewNotes,
        String rejectionReason,
        String reviewedAt,
        Long createdSocietyId,
        String createdSocietyName,
        String createdAt,
        String updatedAt
) {
    public static SocietyCreationRequestResponse from(SocietyCreationRequest req) {
        return new SocietyCreationRequestResponse(
                req.getId(),
                req.getReferenceCode(),
                req.getPrimaryContactName(),
                req.getPrimaryContactEmail(),
                req.getPrimaryContactPhone(),
                req.getSocietyOfficialEmail(),
                req.getSecondaryContactName(),
                req.getSecondaryContactPhone(),
                req.getSecondaryContactEmail(),
                req.getSocietyName(),
                req.getRegistrationNumber(),
                req.getSocietyType(),
                req.getTotalFlats(),
                req.getNumberOfWings(),
                req.getAddress(),
                req.getCity(),
                req.getState(),
                req.getPostalCode(),
                req.getManagementMethod(),
                req.getDocumentUrl(),
                req.getDocumentFilename(),
                req.getDocumentSizeBytes(),
                req.getStatus().name(),
                req.getReviewerUser() != null ? req.getReviewerUser().getId() : null,
                req.getReviewerUser() != null ? req.getReviewerUser().getFullName() : null,
                req.getReviewNotes(),
                req.getRejectionReason(),
                req.getReviewedAt() != null ? req.getReviewedAt().toString() : null,
                req.getCreatedSociety() != null ? req.getCreatedSociety().getId() : null,
                req.getCreatedSociety() != null ? req.getCreatedSociety().getName() : null,
                req.getCreatedAt() != null ? req.getCreatedAt().toString() : null,
                req.getUpdatedAt() != null ? req.getUpdatedAt().toString() : null
        );
    }
}
